import { ButtonBase, Grid2 as Grid, Paper, Typography } from "@mui/material";
import PropTypes from "../utils/propTypes";
import { ImageHolder } from "./ImageHolder";

const InfoElement = ({ imageUrl, title, subtitle, onClick }) => {
    return (
        <ButtonBase sx={{ width: "100%" }} onClick={onClick}>
            <Paper sx={{ display: "flex", width: "100%" }}>
                <ImageHolder
                    src={imageUrl}
                    sx={{
                        minWidth: "5rem",
                        width: "5rem",
                        height: "5rem",
                        objectFit: "cover",
                        borderRadius: "50%",
                        margin: ".25rem",
                        background: "gray",
                        float: "left",
                    }}
                />
                <Grid
                    container
                    flexGrow={1}
                    sx={{ flexGrow: 1, alignContent: "center" }}
                >
                    <Grid size={10}>
                        <Typography
                            variant="h4"
                            sx={{
                                textAlign: "left",
                                textOverflow: "ellipsis",
                                alignSelf: "flex-end",
                            }}
                        >
                            {title}
                        </Typography>
                    </Grid>
                    <Grid size={12} sx={{ borderTop: "1px solid black" }}>
                        <Typography variant="h5" sx={{ textAlign: "left" }}>
                            {subtitle}
                        </Typography>
                    </Grid>
                </Grid>
            </Paper>
        </ButtonBase>
    );
};

//Proptypes generated by copilot
InfoElement.propTypes = {
    imageUrl: PropTypes.string.isRequired,
    title: PropTypes.string.isRequired,
    subtitle: PropTypes.string.isRequired,
    onClick: PropTypes.func,
};

export { InfoElement };
