name: Build and Deploy API to Staging Host

on:
    # Trigger on push to the main branch
    #  push:
    #    branches:
    #      - main

    # Allows manual execution from any branch
    workflow_dispatch:
        inputs:
            branch:
                description: "Branch to deploy" # User chooses the branch to deploy
                required: false
                default: "main" # Default branch if no input is provided

jobs:
    build-and-deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.inputs.branch || github.ref_name }}

            - name: Create .env File
              run: |
                  cat <<EOF > .env
                  DB_HOST=${{ secrets.DB_HOST }}
                  DB_PORT=${{ secrets.DB_PORT }}
                  DB_USER=${{ secrets.DB_USER }}
                  DB_PASSWORD=${{ secrets.DB_PASSWORD }}
                  FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}
                  FIREBASE_PRIVATE_KEY_ID=${{ secrets.FIREBASE_PRIVATE_KEY_ID }}
                  FIREBASE_PRIVATE_KEY=${{ secrets.FIREBASE_PRIVATE_KEY }}
                  FIREBASE_CLIENT_EMAIL=${{ secrets.FIREBASE_CLIENT_EMAIL }}
                  FIREBASE_CLIENT_ID=${{ secrets.FIREBASE_CLIENT_ID }}
                  FIREBASE_AUTH_URI=${{ secrets.FIREBASE_AUTH_URI }}
                  FIREBASE_TOKEN_URI=${{ secrets.FIREBASE_TOKEN_URI }}
                  FIREBASE_AUTH_PROVIDER_CERT_URL=${{ secrets.FIREBASE_AUTH_PROVIDER_CERT_URL }}
                  FIREBASE_CLIENT_CERT_URL=${{ secrets.FIREBASE_CLIENT_CERT_URL }}
                  FIREBASE_UNIVERSE_DOMAIN=${{ secrets.FIREBASE_UNIVERSE_DOMAIN }}
                  EOF

            - name: Build Docker Image
              run: |
                  docker buildx build --network=host -t bg-api ./api

            - name: Save and Transfer Docker Image to Server
              run: |
                  docker save bg-api -o bg-api.tar
                  ssh-keyscan -t ed25519 ${{ secrets.SSH_STAGING_HOST }} >> ~/.ssh/known_hosts
                  scp bg-api.tar ${{ secrets.SSH_USER }}@${{ secrets.SSH_STAGING_HOST }}:/tmp/bg-api.tar

            - name: Deploy Application via SSH
              run: |
                  ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_STAGING_HOST }} << 'EOF'
                    CONTAINER_NAME=bg-api_app
                    IMAGE_TAR=/tmp/bg-api.tar
                    echo "Container Name: $CONTAINER_NAME"
                    echo "Image .tar Name: $IMAGE_TAR"

                    # Load the Docker image
                    echo "Loading $IMAGE_TAR"
                    docker load -i "$IMAGE_TAR"

                    # Stop and remove old container if it exists
                    echo "Stopping running containers..."
                    docker stop "$CONTAINER_NAME" || true
                    echo "Removing previous containers..."
                    docker rm "$CONTAINER_NAME" || true

                    # Run the new container on port 5173
                    echo "Running container: $CONTAINER_NAME"
                    docker run -d --name "$CONTAINER_NAME" -p 3000:3000 bg-api

                    # Clean up image tar file
                    echo "Cleaning up image file..."
                    rm -f "$IMAGE_TAR"
                  EOF
