# https://snyk.io/
# https://github.com/snyk/actions/tree/master/node
name: Snyk Vulnerability Scan

on:
    # Trigger on push to the main branch
    # push:
    #  branches:
    #    - main

    # Allows manual execution from any branch
    workflow_dispatch:
        inputs:
            branch:
                description: "Branch to deploy" # User chooses the branch to deploy
                required: false
                default: "main" # Default branch if no input is provided

jobs:
    snyk-vulnerability-scan:
        runs-on: self-hosted
        timeout-minutes: 60
        steps:
            - uses: actions/checkout@master
            - name: Run Snyk to check for vulnerabilities
              uses: snyk/actions/node@master
              env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
